@startuml
'https://plantuml.com/sequence-diagram

actor "EmployeeService" as ES
participant "Employee Service" as S
database "Employee" as E
database "User" as U

' Create New Employee
ES -> S: CreateEmployeeRequest
S -> U: find user
U -> S: user
S -> E: find employee (check uniq num)

S-> S: validate data
S-> E: create employee

E -> S: employee

S -> ES: CreateEmployeeResponse
@enduml